behaviors:
  KartAgentBC:
    trainer_type: ppo
    hyperparameters:
      batch_size: 120
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
    # Add Behavioral Cloning configuration
    behavioral_cloning:
      demo_path: C:\Users\DELL\Desktop\AI-Racing-Karts - Imitation\Assets\Demonstrations\KartAgent.demo 
      strength: 0.5 
